---
- name: ensure ltb dependency packages are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - nginx
    - php5-fpm
    - php5-ldap
    - php5-mcrypt

- name: ensure that mcrypt module is enabled
  command: php5enmod mcrypt creates=/etc/php5/fpm/conf.d/20-mcrypt.ini
  notify:
    - restart php5-fpm

- name: ensure that ltb group exists
  group:
    name: ltb
    state: present

- name: ensure that ltb user exits
  user:
    name: ltb
    group: ltb
    home: /srv/ltb
    createhome: yes
    shell: /bin/bash
    state: present

- name: ensure /var/cache/ansible directory exists
  file:
    path: /var/cache/ansible
    owner: root
    group: root
    mode: 0755
    state: directory

- name: download the ltb self service password install package
  get_url:
    url: "{{ ltb_download_url }}"
    dest: /var/cache/ansible/ltb.tar.gz

- name: unarchive ltb to /srv/ltb
  command: tar --strip-components 1 -xvzf /var/cache/ansible/ltb.tar.gz
           chdir=/srv/ltb
           creates=/srv/ltb/index.php

- name: ensure files under /srv/ltb are owned by ltb user
  file:
    path: /srv/ltb
    owner: ltb
    group: ltb
    recurse: yes

- name: update /srv/ltb/conf/config.inc.php from template
  template:
    src: srv/ltb/conf/config.inc.php
    dest: /srv/ltb/conf/config.inc.php
    owner: ltb
    group: ltb
    mode: 0600

- name: update /srv/ltb/lang/en.inc.php from template
  template:
    src: srv/ltb/lang/en.inc.php
    dest: /srv/ltb/lang/en.inc.php
    owner: ltb
    group: ltb
    mode: 0600

- name: update /etc/php5/fpm/pool.d/ltb.conf from template
  template:
    src: etc/php5/fpm/pool.d/ltb.conf
    dest: /etc/php5/fpm/pool.d/ltb.conf 
    owner: root
    group: root
    mode: 0644
  notify:
    - restart php5-fpm

- name: update /etc/nginx/sites-available/ltb from template
  template:
    src: etc/nginx/sites-available/ltb
    dest: /etc/nginx/sites-available/ltb
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: ensure /etc/nginx/sites-enabled/ltb exists and links to ../sites-available/ltb
  file:
    path: /etc/nginx/sites-enabled/ltb
    src: ../sites-available/ltb
    force: yes
    state: link
  notify:
    - restart nginx

- name: ensure that there is not a hostname collision with the nginx default host
  lineinfile:
    dest: /etc/nginx/sites-available/default
    regexp: '^(\s+)(server_name {{ ltb_hostname }};.*)$'
    backrefs: yes
    line: '\1#\2'
    state: present
  notify:
    - restart nginx

- name: ensure ltb services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - nginx
    - php5-fpm

